In [ ]:
import pandas as pd

In [3]:
df = pd.read_csv("titanic.csv")

In [4]:
#6. Cabin Information Value  crosstab(age bin , sex , famsize,cabin)
# Does having cabin information recorded correlate with socioeconomic status and survival probability?

In [8]:
#frist to convert into numeric
df["Cabin_Sta"] = df["Cabin"].notnull().astype(int)

In [9]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_Sta
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [13]:
pd.crosstab(df["Cabin_Sta"] , df["Survived"] , normalize="index").round(3)

Survived       0      1
Cabin_Sta
0          0.700  0.300
1          0.333  0.667

In [12]:
pd.crosstab(df["Cabin_Sta"] ,df["Pclass"] , normalize="index").round(3)

Pclass         1      2      3
Cabin_Sta
0          0.058  0.245  0.697
1          0.863  0.078  0.059

In [14]:
#7. Children's Advantage Analysis
# Did children receive a survival advantage, and at what age threshold does survival probability significantly decrease?

In [2]:
import pandas as pd  
df2 = pd.read_csv("titanic.csv")
df2.head(20)
df2.to_csv("Clean_Titanic.csv" , index=False)

In [24]:
# #df_bins = pd.cut(df1["Fam_size"] , bins = age_bins , labels=age_label)
# age_bins = [0,2,4,15]
# age_label = ["Sm_Fam" , "Mid_Fam" , "Lar_Fam"]
# df_bins = pd.cut(df1["Fam_size"] , bins = age_bins , labels=age_label)
# df_bins.head(20)

df2 = pd.read_csv("titanic.csv")
df2["Fam_size"] = df2["SibSp"]+df2["Parch"]
df2["Fam_size"].describe()
age_size = [0,5,10,15]
age_label = ["small_kid" , "mod_kid" , "semi_large_kid"]

df_bin = pd.cut(df2["Fam_size"] , bins=age_size,labels=age_label )
df_bin.head(40)
print(df_bin.median)

<bound method Series.median of 0      small_kid
1      small_kid
2            NaN
3      small_kid
4            NaN
         ...
886          NaN
887          NaN
888    small_kid
889          NaN
890          NaN
Name: Fam_size, Length: 891, dtype: category
Categories (3, str): ['small_kid' < 'mod_kid' < 'semi_large_kid']>

In [ ]:
print(df_bin.median())
# make the new column and then sort and then find the median

TypeError: 'Categorical' with dtype category does not support operation 'median'