In [2]:
import pandas as pd
df = pd.read_excel("Product-Sales-Region.xlsx")
df.head(5)

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[us]
 1   Region         1500 non-null   str
 2   Product        1500 non-null   str
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   str
 6   CustomerType   1500 non-null   str
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   str
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   str
 11  Promotion      1130 non-null   str
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   str
 14  CustomerName   1500 non-null   str
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[us]
 17  DeliveryDate   1500 non-null   datetime64[us]
 18  RegionManager  1500 non-null   str
dtypes: datetime64[us](3), float64(4), int64(2), str(10)
memory usage: 320.3 KB

In [4]:
import pandas as pd
import numpy as np

# Select numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Store results
results = []

for col in num_cols:

    mean_val = df[col].mean()
    median_val = df[col].median()
    mode_val = df[col].mode()[0]

    skew_val = df[col].skew()
    kurt_val = df[col].kurt()

    # Determine skewness type
    if skew_val > 0:
        skew_type = "Positively Skewed (Right Tail)"
    elif skew_val < 0:
        skew_type = "Negatively Skewed (Left Tail)"
    else:
        skew_type = "Symmetric"

    # Determine kurtosis type
    if kurt_val > 0:
        kurt_type = "Leptokurtic"
    elif kurt_val < 0:
        kurt_type = "Platykurtic"
    else:
        kurt_type = "Mesokurtic"

    results.append([
        col,
        round(mean_val, 2),
        round(median_val, 2),
        round(mode_val, 2),
        round(skew_val, 2),
        skew_type,
        round(kurt_val, 2),
        kurt_type
    ])

# Create summary dataframe
eda_summary = pd.DataFrame(results,
                           columns=[
                               "Column",
                               "Mean",
                               "Median",
                               "Mode",
                               "Skewness",
                               "Skew Type",
                               "Kurtosis",
                               "Kurtosis Type"
                           ])

print(eda_summary)

         Column     Mean   Median   Mode  Skewness  \
0      Quantity    10.41    11.00   7.00      0.00
1     UnitPrice   298.83   294.74  67.38      0.02
2      Discount     0.07     0.05   0.00      0.03
3    TotalPrice  2919.99  2174.72   6.97      0.97
4      Returned     0.25     0.00   0.00      1.17
5  ShippingCost    27.51    27.10  29.31      0.01

                        Skew Type  Kurtosis Kurtosis Type
0  Positively Skewed (Right Tail)     -1.21   Platykurtic
1  Positively Skewed (Right Tail)     -1.21   Platykurtic
2  Positively Skewed (Right Tail)     -1.36   Platykurtic
3  Positively Skewed (Right Tail)      0.08   Leptokurtic
4  Positively Skewed (Right Tail)     -0.64   Platykurtic
5  Positively Skewed (Right Tail)     -1.19   Platykurtic

In [5]:
df.columns

Index(['Date', 'Region', 'Product', 'Quantity', 'UnitPrice', 'StoreLocation',
       'CustomerType', 'Discount', 'Salesperson', 'TotalPrice',
       'PaymentMethod', 'Promotion', 'Returned', 'OrderID', 'CustomerName',
       'ShippingCost', 'OrderDate', 'DeliveryDate', 'RegionManager'],
      dtype='str')

In [6]:
df["Region"].value_counts()

Region
East       311
North      309
Central    301
South      295
West       284
Name: count, dtype: int64

In [7]:
df["Product"].value_counts()

Product
Tablet     240
Laptop     226
Monitor    212
Printer    211
Chair      209
Desk       207
Phone      195
Name: count, dtype: int64

In [8]:
df["StoreLocation"].value_counts()

StoreLocation
Store D    400
Store A    372
Store C    365
Store B    363
Name: count, dtype: int64

In [9]:
df["PaymentMethod"].value_counts()

PaymentMethod
Online         323
Cash           312
Credit Card    299
Debit Card     290
Gift Card      276
Name: count, dtype: int64

In [13]:
df["Product"].unique()

<ArrowStringArray>
['Laptop', 'Phone', 'Desk', 'Chair', 'Monitor', 'Tablet', 'Printer']
Length: 7, dtype: str

In [14]:
df.groupby(["Region" , "Product"])["TotalPrice"].sum()

Region   Product
Central  Chair      113029.4415
         Desk       110743.9290
         Laptop     139219.5800
         Monitor    107231.8960
         Phone       72442.8265
         Printer    139174.8675
         Tablet     165311.1440
East     Chair      107210.1945
         Desk       118254.6630
         Laptop     135461.4075
         Monitor    121548.1315
         Phone      145231.2030
         Printer    149017.8450
         Tablet     106910.2735
North    Chair      136982.5300
         Desk       170637.9805
         Laptop     122643.5660
         Monitor    172222.0435
         Phone       79577.4530
         Printer    128877.2280
         Tablet     157017.1790
South    Chair      150978.0410
         Desk        68565.6710
         Laptop     157696.0205
         Monitor    101689.4455
         Phone      121325.6950
         Printer    122090.8650
         Tablet     105422.4490
West     Chair      114389.2710
         Desk        87064.4210
         Laptop     129396.6675
         Monitor    148937.8760
         Phone       78585.6735
         Printer    145226.6100
         Tablet     149878.3400
Name: TotalPrice, dtype: float64

In [18]:
df.groupby(["Salesperson","Region"])["TotalPrice"].sum()

Salesperson  Region
Alice        Central    155527.4200
             East       163494.8505
             North      114607.5655
             South      153319.7935
             West       199216.2105
Bob          Central    146204.1230
             East       194771.8440
             North      168017.5910
             South      154037.6065
             West       133749.3570
Carlos       Central    156260.9495
             East       126261.6435
             North      175749.3075
             South      116629.0320
             West       132265.7835
Diana        Central    122602.5440
             East       131527.0415
             North      144354.9705
             South      148285.5005
             West       129798.1930
Eva          Central    154827.6415
             East       156856.0745
             North      147226.5680
             South      107164.8505
             West       132594.4450
Frank        Central    111731.0065
             East       110722.2640
             North      218001.9775
             South      148331.4040
             West       125854.8700
Name: TotalPrice, dtype: float64

In [19]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [21]:
df[df["PaymentMethod"] == "Online"] \
    .groupby("Salesperson")["TotalPrice"] \
    .sum()

Salesperson
Alice     196187.2850
Bob       207004.9965
Carlos    160638.7935
Diana     141660.7155
Eva       105056.7335
Frank     160566.6260
Name: TotalPrice, dtype: float64